name: 'Docker'

on:
    workflow_run:
        workflows: ['Version']
        types:
            - completed

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        # add to github repository secrets:
        # DOCKERHUB_USERNAME
        # DOCKERHUB_TOKEN
        # DOCKER_IMAGENAME
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # update Docker tags username/imagename:version
        - name: Build and push Api Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./src/WebApi/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{needs.versionize.outputs.version}}
        #   tags: username/imagename:version